---
- hosts: localhost
  roles:
    - common
    - font
    - go
    - i3
    - joplin
    - keepassxc
    - mysql
    - neovim
    - php
    - pkg_manager
    - rg
    - terminal
    - tmux
    - urxvt
    - vim-anywhere
    - zsh
    - pandoc
    - todotxt
