---
- hosts: localhost
  roles:
    - pkg_manager
    - nix
    - zsh
    - common
    - font
    - terminal
    - urxvt
    - go
    - git
    - github
    - i3
    - keepassxc
    - mysql
    - neovim
    - php
    - rg
    - tmux
    - pandoc
    - gemini-cli
    - {role: "tfenv", "tags": "tf"}
    - pyenv
    - goland
