default_xdg_config_home: "{{ ansible_user_dir }}/.config"

config_dir: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"

node_version: v15.5.0
activitywatch_version: v0.10.0
firacode_version: 5.2
go_version: go1.15.6
go_mockery_version: 2.4.0
go_golangcilint_version: 1.33.0
joplin_gui_version: 1.5.9
ruby_version: 2.7.1
rbenv_version: v1.1.2
bat_version: 0.17.1
rg_version: 12.1.1
