default_xdg_config_home: "{{ ansible_user_dir }}/.config"

config_dir: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"

node_version: v24.5.0
activitywatch_version: v0.13.2
firacode_version: v6.2
go_version: go1.24.0
go_mockery_version: v3.5.4
go_golangcilint_version: v2.4.0
ruby_version: v3.4.4
rbenv_version: v1.3.2
bat_version: v0.25.0
rg_version: 14.1.1
tmux_version: v3.5a
tpm_version: master
pandoc_themes_version: master
hack_font_version: v3.003
fnm_version: v1.38.1
terraform_version: 1.12.0
neovim_version: v0.11.3


packages:
  - build-essential
  - git
  - curl
  - ripgrep
  - fd-find
  - python3-full
