default_xdg_config_home: "{{ ansible_user_dir }}/.config"

config_dir: "{{ ansible_env.XDG_CONFIG_HOME | default(default_xdg_config_home) }}"

node_version: v20.2.0
activitywatch_version: v0.12.2
firacode_version: 5.2
go_version: go1.20.4
go_mockery_version: 2.14.0
go_golangcilint_version: 1.52.2
joplin_gui_version: v2.4.8
ruby_version: 2.7.1
rbenv_version: v1.2.0
bat_version: 0.23.0
# rg_version: 12.1.1
